WIP: Basic integration testing
RHsyseng/jenkins-on-openshift pull request #113
Opened 2018-02-05 18:33 UTC by jcpowermac

2018-02-05 18:36 UTC, jcpowermac commented
Current problems:
- IP address of `clusterhost`
- Release pipeline sends emails pipeline fails if unable to send.

2018-02-05 23:38 UTC, jcpowermac commented
@codificat ok I think this is ready to go.

2018-02-06 12:04 UTC, codificat requested changes
This is awesome, thanks!!

A few minor comments but otherwise looks [very] good to me.

2018-02-06 12:04 UTC, codificat commented on tests/alternative/README.md
> +```
I believe this should read:
```
cd jenkins-on-openshift/tests
bash alternative/run.sh
```

2018-02-06 12:04 UTC, codificat commented on tests/tests-openshift-template.yaml
> +      type: ImageChange
I think we want a `ConfigChange` trigger as well... and/or document that a build of ansible should be performed before running the test pipeline

2018-02-06 12:04 UTC, codificat commented on tests/README.md
> +- Permissions to use BuildConfig objects
Maybe make it explicit that builds should happen on properly subscribed RHEL7 nodes?

2018-02-06 12:04 UTC, codificat commented on tests/README.md
> +
... and then:

`oc start-build jenkins-on-openshift-tests`

2018-02-06 12:04 UTC, codificat commented on tests/Jenkinsfile
> +                            sh "oc login ${cluster} --username ${env.OCP_USR} --password ${env.OCP_PSW} --insecure-skip-tls-verify"
Need to surround the password in quotes

2018-02-06 14:08 UTC, merged